# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180117_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=3)),
                ('birthday', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField()),
            ],
        ),
    ]
