# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180117_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
