# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_user_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
